// Define the repository information in these attributes
:repository-owner: ricardoquesasda
:repository-name: bluepad32-arduino
:project-name: Bluepad32

= {project-name} library for Arduino =


image::https://lh3.googleusercontent.com/pw/AM-JKLWUZS_vlkMmd3o8EKzXlYCS0uriEW_gXfOoiFqZlABJi_dM1GWYHGafrdMnTP-VHgVdCdVA4pUageZgyI98RH1SHtydac2yyrx_vJVXgWPYBFN-SJoOikdlGuOowPoDqYOwfKU39yketYPJyRJlIPwjEw=-no[gamepads]


Enables gamepad support for NINA-based boards, like:

* Arduino Nano RP2040 Connect
* Arduino Nano 33 IoT
* Arduino MKR WiFi 1010
* etc.

What's unique about these boards, is that they have two processors:

* The main one, where the Arduino sketches run
* And the NINA (ESP32), which is used just to provide WiFi connectivity.

In order to use this library, you have to flash the Bluepad32 firmware in the NINA (ESP32) processor.
This is a simple step that needs to be done just once, and can be undone at any time.
More info about Bluepad32 for NINA here:

* Instructions: https://gitlab.com/ricardoquesada/bluepad32/-/blob/master/docs/plat_nina.md
* Download: https://gitlab.com/ricardoquesada/bluepad32/-/releases


With this library you can use any modern Bluetooth gamepad in Arduino. Some of the supported gamepads, but not limited to, are:

* DualSense (PS5)
* DualShock 4 (PS4)
* DualShock 3 (PS3)
* Switch gamepad
* Switch Joy-cons
* Xbox One S
* WiiMote and extensions
* Wii U gamepad
* Android gamepads
* Window gamepads
* 8Bitdo gamepads
* iCade
* and more

For a complete list, see: https://gitlab.com/ricardoquesada/bluepad32/-/blob/main/docs/supported_gamepads.md

== Use cases ==

You can use this library to:

* Create a video game
* Or control a car / robot
* Or control LEDs, motor, etc.
* Or to draw a curtain, open a window, control a fan, etc.
* etc.

== License ==

Copyright (c) 2021 Ricardo Quesada

SPDX-License-Identifier: Apache 2.0 or LGPL-2.1-or-later

